pupene: pupene::JsonReader Class Reference
pupene::JsonReader Class Reference
#include <json-puppers.h>
Public Member Functions
template<typename T >
PupPolicy begin (T &, const Meta &meta)
void end (const Meta &)
JsonReader (std::istream &in)
template<typename T , typename = enable_if_puppable<T>>
void pup (T &value, const Meta &meta)
~JsonReader () override=default
Public Member Functions inherited from pupene::Pupper< JsonReader >
PupPolicy begin_impl (T &value, const Meta &meta)
void end_impl (const Meta &meta)
void pup_impl (T &value, const Meta &meta)
Pupper ()=default
virtual ~Pupper ()=default
Friends
std::ostream & operator<< (std::ostream &out, const JsonReader &reader)
Detailed Description
Definition at line 81 of file json-puppers.h.
Constructor & Destructor Documentation
JsonReader()
pupene::JsonReader::JsonReader (std::istream & in) inline explicit
Definition at line 83 of file json-puppers.h.
References JsonReader().
Referenced by pupene::from_json(), and JsonReader().
~JsonReader()
pupene::JsonReader::~JsonReader () override default
Member Function Documentation
begin()
template<typename T > PupPolicy pupene::JsonReader::begin (T & , const Meta & meta) inline
Definition at line 91 of file json-puppers.h.
References pupene::pup_object, pupene::Meta::type, and pupene::Meta::Value.
end()
void pupene::JsonReader::end (const Meta &)
Definition at line 39 of file json-puppers.cpp.
pup()
template<typename T , typename = enable_if_puppable<T>> void pupene::JsonReader::pup (T & value, const Meta & meta) inline
Definition at line 107 of file json-puppers.h.
References pupene::Meta::Array.
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const JsonReader & reader) friend
Definition at line 47 of file json-puppers.cpp.
The documentation for this class was generated from the following files:
include/json-puppers.h
src/json-puppers.cpp