pupene: pupene::Meta Struct Reference
pupene::Meta Struct Reference
Holds name and type of objects.
#include <traits.h>
Public Types
enum Type { Type::Array = 1, Type::Object, Type::Value }
Public Member Functions
Meta ()
Meta (const char *name, Type type=Type::Value)
~Meta ()=default
Public Attributes
const char * name
The name typically matches the name of the represented field.
const Type type = Type::Value
Detailed Description
Holds name and type of objects.
Definition at line 7 of file traits.h.
Member Enumeration Documentation
Type
enum pupene::Meta::Type strong
Enumerator
Array
Object
Value
Definition at line 8 of file traits.h.
Constructor & Destructor Documentation
Meta() [1/2]
pupene::Meta::Meta () inline
Definition at line 12 of file traits.h.
References Meta().
Meta() [2/2]
pupene::Meta::Meta (const char * name, Type type = Type::Value) inline
Definition at line 13 of file traits.h.
References name, and type.
Referenced by Meta(), pupene::fns::pup(), pupene::fns::pup_object(), and pupene::fns::pup_object_container().
~Meta()
pupene::Meta::~Meta () default
Member Data Documentation
name
const char* pupene::Meta::name
The name typically matches the name of the represented field.
Definition at line 18 of file traits.h.
Referenced by pupene::DebugPupper< Wrapped >::begin(), pupene::DebugPupper< Wrapped >::end(), Meta(), pupene::DebugPupper< Wrapped >::pup(), and pupene::fns::pup_object().
type
const Type pupene::Meta::type = Type::Value
Definition at line 19 of file traits.h.
Referenced by pupene::JsonWriter::begin(), pupene::JsonReader::begin(), Meta(), and pupene::fns::pup_object().
The documentation for this struct was generated from the following file:
include/traits.h